# These configurations specifically for the current service where it defines.

services:
  user-service:
    image: akashvai/user-authentication-authorization-service:latest
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=9001
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
    ports:
      - "9532:9001"
    depends_on:
      - postgres
    networks:
      - db_network
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: spacedb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - db_network
networks:
  db_network:
    driver: bridge